language: node_js
node_js:
- '8'
services:
- docker
cache: yarn
before_install: yarn global add json
script:
- cd prometheus && yarn install && cd ..
- yarn run lint
deploy:
- provider: npm
  email: andersonba@me.com
  api_key:
    secure: T+FrSac2O3Byjy/1xkLzwWtYCuudtOEuk71g6A3uqHJzjInWNI4V9dcITDAhPtRzv4TrtFHlKwPSbCbG2Vl67dLKJ3iylx5XpINcr3OYkePzLkxJTopaGfcM026Msi6Kv0tIofM/cL1wJaTGefzN6UlSgcSqkEW0FQVaVG2VwAaCzSmQ3Tlp+wY/0a+JE6RgXl9RYBy3+sZymzc1KCTFp5Kyf/++uD4Axl0V6tCldnIS2bGKBs7d5E+/XNp2wxvRl5CzDyE0RdLRiEfwp0sJCwgqQ+hxR2RP4cA7rgjFr+EP053qUCHyABTO0Rw8MZZpNIncK7TdlDUptZhX1vxGN2t5VZkCWN2pu8ewb5eJ/Ajv9EsTkE0cYnx+lM1Mn4G5t8HXVffCIkOopNT14NjOpEtq0ovAKrJY8Z+K+wFbwult1Y2+lLpEQB3YjLUntKAP+ONQWmSGUwV5tCEGuIUTm8wMfOkVqhlDlCazykF1RPSa5hwxL/XnFm3HAXgNpRb4CE/KjZ2E6pYwWE4DjTqw2uK4xLqEDcy/CW+H2XCptdStTxk8ByLOvZXSiU2shhyHoZ72kT2nCt4AgrWd8RFfH380hOMgFhOWw7t6i+9N2GDF/1B9JZxmMKviOTefT6hAt4xucnyRi3OSEV88yQeaR+amlDI2E9Mj4+AHBDgOlMA=
  on:
    tags: true
    repo: andersonba/puppeteer-assets
- provider: script
  script: bash resources/docker_push.sh
  on:
    tags: true
    repo: andersonba/puppeteer-assets
