language: node_js
node_js:
- '8'
cache: yarn
before_install: yarn global add json
script:
- cd prometheus && yarn install && cd ..
- yarn run lint
deploy:
- provider: npm
  email: andersonba@me.com
  api_key:
    secure: aVfxvM2DRMjxA7TCznILGUf48RW6X3qSxB0pJNrXrpjz4iLbuOgIPV9x/HX0cfrwRVsEf8BAQa5ponmD4TAFefQ/O1P6y4ie+7LylXIhBQ1YbHlK26TYfGVP5OuD540RjMy2iRS1HqcMn7kwVlf9bXXrhOES5NoA9BiPPWVH7XLOONF5/pxyD03DAU8N36yhoYLP5t0C+XvmnD4cjkA10rph/agcMGUdqRVu7XhhyE85XjEihY12xWnJgm9I4FBl2XYeyXc3g+Y15MXXN0Z+cw9qV/HMh1AvIGLhjeKz4MU+xY5pxEyteOOIvI3paqnMajSvaD2vy6dLmAz05VMyYgjAl4rbMGS6PWJ54Pf1FUwAk63ChAFGL6IAQpJaOE9aB4I3As7tNFFUXnVmwmP2qo+lFVMNX+lozmargwOhSsqsqAUrD116AbpQH/WqciTs6IaOBEeSP4iWZcgRIFJ5CNCt2pqii9P6Ox+MvhElOWAKaDZTCrWFJrefrMEIMeDSlpvI4creem2i8n34th8UIz31Q70ta4PMYrVFulMbWWxWQhUbZSdcSAKTFXHGepQQ3szrCIdRrQX+yopWSmpbOAwPmxPbYkYH7RLp7q0s0qU4xIUxra7nX4hTHngkK4LybufC70dUEcyuOqIfNO3sMUowORrGE8mWUcwryxEggZo=
  on:
    tags: true
    repo: andersonba/puppeteer-assets
- provider: script
  script: bash resources/docker_push.sh
  on:
    tags: true
    repo: andersonba/puppeteer-assets
env:
  global:
  - secure: VGqe9cZMZWs3u+90mAA/XROYBD2tQMXRUcSDGDWAQVJW+InQJwP+IuGR7FUvZBJKnRTdHR3PBVw0DYHOTomHVMhNnoUEXYzki1OsL4UHFvFIbF0RpavkqRGVn/OxZM0O0KN5HKnN3mZQlksV0jyoUOlJ8ymJxBtxL7jg8Y7xFtLH2J0DwVWXfmCwBnGun4aJEYp86kLRJOkYlGbhzSVvShK5dA+d/MR6MslR+/yPdEz2Ag3sV61tAS9nC3PAedkqRgSR3U2fhzGLr6MJEXVVEaKhWVAJwMI1sYIe2GnqgQ9A4/loeehTm61tr3aa266/fmrzUVgFFyXGFxZqq4ddxc/LBvhAVEIaU+G7YXcuvqDrQhFm8RRvBCCMVrMoP1Txefocj+jXUbMuLwTj4aXN6Do3G+8s0+nvwpurzhqTqkXc7OWR159tVkh4QOrIROXsmI99st85uW5zcwN7ZLhiXZWmO7KvSkE2ZgDfY8r31v3Y5BbXj3GprJw1Vz6Dewf6yASJbYoY2mcnHUAerIfjhI2x/rZsE9oPIZcMDnBaoqf2H9lkeCIrjGRAbHrNWyZCGyCrReeAfgBkbmo3G5uMPFpzDF/B1OUN4cOv+YoadpSa4VrLW3xusLww3tzRoti2KoLLx3boe4a/WN51KBoK2tm8JdKP9OweSsjulkwzOLw=
  - secure: Ov8KjzzkKDg01jGLy7tvmGFR7s2Z8k/YYKOTE9Fd4kBOfXgj02qCjV9Pxe8Lzk2x7ELCDMBNu2AKL4s8WYPpu2iaVcErTdS7omAwNrzg4YeOohpCa5F+tdDIKSCkHuOzt7XRr0xRp4praGiTlPiYGO0qH5yHSc6TnvOJ7NHaD9dppfnyAMEl4b3iqARo/YwBEABIDKSE3ahSBucgZ4nv384SAiPLUKt47O8BHdIYYg29vgAX+C+YJ/BRYWPnTzIK6+Zzz8ttHZ8vbAvNHV4qEtEI+9QRaY3zwTdUK/nrKN00EzWCP2HYgqXSKIiytO2D/7LyCP5d5S5JUM5gxnkmTOHIEmgdlU0bPKN/uE4h/fBkjGYGhmT+bIpBY2fVtx53p2fVyc8cAMDOw6GOWB9j0Y3ccf6wNfcQ6YuqiaF40qdG5oWoYVnkaJebsvJRD9S2pd+QWqsCYOH3nbmvxtMXaT6+srpkQWXEUZPzQ7WAmRGnEnkKI6mcHFaDHJqKHtDbd+2M6F5vDcLQpyk1/va8Gdl/i1AzzKwG8LwlFyd2t3GZuz5kVMy4qm66FKT1gjDSgSun41+DIdHNBMZNW527Detj/aBEqLTvY7QLZbg7C3108SvCYlnBZ7ABcbFZI0/ApvQzW1Iu5nibQYK9I0B3VQjCFHCJb1mmphhqcu2/mHE=
  - secure: DB1R2k8/FxEKk/oM3cnVxBekUcHBMrzJIeSvTwMU4EakeLJb8VvFEVfvj4buQ0hDKg/FhhGTNHChzTzs96SN1gojqtIGZljBMTLjNNtPo8YqTE1sqnXuACq45vQZewIKQj3sXgDYFXI0W4y2bIDgXCJTMjyys1n0nkuUr5CEVWlKy1nGoaXQS3jEBPOzlN/J+O39Wo6KpFC5m1S7lL9ctMiUlAaxXTpSQYUn13xQK8YmLhMAuM4tbn7KDz9iKsGMHRZ2SUB5oGlG8Me7spE970+n+zmKl/whr3f/DUN6fFNYB3AkerQH+Mttzrzg1ywSYJszz/tR1lTBqHX8YQ+KfzrvSMV/nJD0lG5gSK6s2GxaOPLeisPFnIHyUph/8yuibbkrYqYGSxA8qLRted3HY4rJdhZhUa5IomG6cXZ2atA8H+Vs5BfdE/wqV1GB3WNXcQlXHvRkz2okm6nghXVGUifC6qYWl31Wost+UPUhFrs4/uvrEgt7/nbfX6Ec6VTD9rLN0Uco9ThHye1VJSiVqN/4qWMabWbN4t8VXZuj73MhrbvptHrxo7yrHcRbbg5XBieTxQgQjgZE0au+d1N/q/f1rrCR+I1P46kp8HKTRSuwumUZ6MHAlmg0MHsgMkCXSaLfR1I9m1BCk+t0BAqUVUrCbWOLojsNvuH1K7qnFiM=
