language: node_js
node_js:
- '8'
services:
- docker
cache: yarn
before_install: yarn global add json
script:
- cd prometheus && yarn install && cd ..
- yarn run lint
deploy:
- provider: npm
  email: andersonba@me.com
  api_key:
    secure: T+FrSac2O3Byjy/1xkLzwWtYCuudtOEuk71g6A3uqHJzjInWNI4V9dcITDAhPtRzv4TrtFHlKwPSbCbG2Vl67dLKJ3iylx5XpINcr3OYkePzLkxJTopaGfcM026Msi6Kv0tIofM/cL1wJaTGefzN6UlSgcSqkEW0FQVaVG2VwAaCzSmQ3Tlp+wY/0a+JE6RgXl9RYBy3+sZymzc1KCTFp5Kyf/++uD4Axl0V6tCldnIS2bGKBs7d5E+/XNp2wxvRl5CzDyE0RdLRiEfwp0sJCwgqQ+hxR2RP4cA7rgjFr+EP053qUCHyABTO0Rw8MZZpNIncK7TdlDUptZhX1vxGN2t5VZkCWN2pu8ewb5eJ/Ajv9EsTkE0cYnx+lM1Mn4G5t8HXVffCIkOopNT14NjOpEtq0ovAKrJY8Z+K+wFbwult1Y2+lLpEQB3YjLUntKAP+ONQWmSGUwV5tCEGuIUTm8wMfOkVqhlDlCazykF1RPSa5hwxL/XnFm3HAXgNpRb4CE/KjZ2E6pYwWE4DjTqw2uK4xLqEDcy/CW+H2XCptdStTxk8ByLOvZXSiU2shhyHoZ72kT2nCt4AgrWd8RFfH380hOMgFhOWw7t6i+9N2GDF/1B9JZxmMKviOTefT6hAt4xucnyRi3OSEV88yQeaR+amlDI2E9Mj4+AHBDgOlMA=
  on:
    tags: true
    repo: andersonba/puppeteer-assets
- provider: script
  script: bash resources/docker_push.sh
  on:
    tags: true
    repo: andersonba/puppeteer-assets
env:
  global:
  - secure: Ov8KjzzkKDg01jGLy7tvmGFR7s2Z8k/YYKOTE9Fd4kBOfXgj02qCjV9Pxe8Lzk2x7ELCDMBNu2AKL4s8WYPpu2iaVcErTdS7omAwNrzg4YeOohpCa5F+tdDIKSCkHuOzt7XRr0xRp4praGiTlPiYGO0qH5yHSc6TnvOJ7NHaD9dppfnyAMEl4b3iqARo/YwBEABIDKSE3ahSBucgZ4nv384SAiPLUKt47O8BHdIYYg29vgAX+C+YJ/BRYWPnTzIK6+Zzz8ttHZ8vbAvNHV4qEtEI+9QRaY3zwTdUK/nrKN00EzWCP2HYgqXSKIiytO2D/7LyCP5d5S5JUM5gxnkmTOHIEmgdlU0bPKN/uE4h/fBkjGYGhmT+bIpBY2fVtx53p2fVyc8cAMDOw6GOWB9j0Y3ccf6wNfcQ6YuqiaF40qdG5oWoYVnkaJebsvJRD9S2pd+QWqsCYOH3nbmvxtMXaT6+srpkQWXEUZPzQ7WAmRGnEnkKI6mcHFaDHJqKHtDbd+2M6F5vDcLQpyk1/va8Gdl/i1AzzKwG8LwlFyd2t3GZuz5kVMy4qm66FKT1gjDSgSun41+DIdHNBMZNW527Detj/aBEqLTvY7QLZbg7C3108SvCYlnBZ7ABcbFZI0/ApvQzW1Iu5nibQYK9I0B3VQjCFHCJb1mmphhqcu2/mHE=
  - secure: DB1R2k8/FxEKk/oM3cnVxBekUcHBMrzJIeSvTwMU4EakeLJb8VvFEVfvj4buQ0hDKg/FhhGTNHChzTzs96SN1gojqtIGZljBMTLjNNtPo8YqTE1sqnXuACq45vQZewIKQj3sXgDYFXI0W4y2bIDgXCJTMjyys1n0nkuUr5CEVWlKy1nGoaXQS3jEBPOzlN/J+O39Wo6KpFC5m1S7lL9ctMiUlAaxXTpSQYUn13xQK8YmLhMAuM4tbn7KDz9iKsGMHRZ2SUB5oGlG8Me7spE970+n+zmKl/whr3f/DUN6fFNYB3AkerQH+Mttzrzg1ywSYJszz/tR1lTBqHX8YQ+KfzrvSMV/nJD0lG5gSK6s2GxaOPLeisPFnIHyUph/8yuibbkrYqYGSxA8qLRted3HY4rJdhZhUa5IomG6cXZ2atA8H+Vs5BfdE/wqV1GB3WNXcQlXHvRkz2okm6nghXVGUifC6qYWl31Wost+UPUhFrs4/uvrEgt7/nbfX6Ec6VTD9rLN0Uco9ThHye1VJSiVqN/4qWMabWbN4t8VXZuj73MhrbvptHrxo7yrHcRbbg5XBieTxQgQjgZE0au+d1N/q/f1rrCR+I1P46kp8HKTRSuwumUZ6MHAlmg0MHsgMkCXSaLfR1I9m1BCk+t0BAqUVUrCbWOLojsNvuH1K7qnFiM=
