path: /metrics
metricName: puppeteer_assets
enableOnDemandQuery: true
onDemandQueryCacheTTL: 300
labels:
  - site
interval: 60000
defaults:
  metrics:
    file: true
    count: true
    size: true
    gzip: true
    countByMimeType: true
    sizeByMimeType: true
    gzipByMimeType: true
  mimeTypes:
    - javascript
  mimeTypesPatterns:
    javascript:
      - javascript
    css:
      - css
  internalPatterns:
    - ^(\/|.\/)
configurations:
  - url: www.andersonba.com
    labels:
      site: andersonba
      unknown: ignore
    internalPatterns:
      - cdn.google.com
    mimeTypes:
      - javascript
      - css
  - url: https://andersonba.github.io/yve-bot/
    labels:
      site: yvebot
    internalPatterns:
      - cdn.andersonba.com
    mimeTypes:
      - javascript
    mimeTypesPatterns:
      javascript:
        - text/javascript
