version: '3'
services:
  server:
    build:
      context: ..
      dockerfile: prometheus/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/prometheus/node_modules

  prometheus:
    image: quay.io/prometheus/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - server
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3001:3000"

volumes:
  prometheus.yml:
  config.example.yml:
