version: "3"

services:
  server:
    build:
      context: ..
      dockerfile: prometheus/Dockerfile
    command: yarn dev
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/prometheus/node_modules
      - ./config.example.yml:/app/config.yml

  prometheus:
    image: quay.io/prometheus/prometheus
    volumes:
      - ./prometheus.ondemand.yml:/etc/prometheus/prometheus.yml
    links:
      - server
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "8080:3000"

volumes:
  prometheus.yml:
  prometheus.ondemand.yml:
  config.example.yml:
