{
 "title": "Assets metrics",
 "description": "Generated by puppeteer-assets",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "page",
    "label": "Page URL",
    "query": "label_values(puppeteer_assets_count, page)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current count",
   "type": "gauge",
   "description": "Total of assets",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(puppeteer_assets_count{page=~\"$page\"})"
    }
   ]
  },
  {
   "title": "Internal count",
   "type": "singlestat",
   "description": "Total of internal assets",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(puppeteer_assets_count{page=~\"$page\", type=\"internal\"})"
    }
   ]
  },
  {
   "title": "Count by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(puppeteer_assets_count{page=~\"$page\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "External count",
   "type": "singlestat",
   "description": "Total of external assets",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(puppeteer_assets_count{page=~\"$page\", type=\"external\"})"
    }
   ]
  },
  {
   "title": "Current size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(puppeteer_assets_size{page=~\"$page\"})"
    }
   ]
  },
  {
   "title": "Internal size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(puppeteer_assets_size{page=~\"$page\", type=\"internal\"})"
    }
   ]
  },
  {
   "title": "Size by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(puppeteer_assets_size{page=~\"$page\"}) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(puppeteer_assets_encoded_size{page=~\"$page\"}) by (type)",
     "legendFormat": "encoded {{type}}"
    }
   ]
  },
  {
   "title": "External size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 12 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(puppeteer_assets_size{page=~\"$page\", type=\"external\"})"
    }
   ]
  },
  {
   "title": "Assets files",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sort(max(puppeteer_assets_file) by (type, url) == on() group_left max(puppeteer_assets_file))"
    }
   ]
  },
  {
   "title": "Size by mime_type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(puppeteer_assets_size_by_mime_type{page=~\"$page\"}) by (mime_type, type)",
     "legendFormat": "{{type}} {{mime_type}}"
    }
   ]
  },
  {
   "title": "Encoded size by mime_type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(puppeteer_assets_encoded_size_by_mime_type{page=~\"$page\"}) by (mime_type, type)",
     "legendFormat": "{{type}} {{mime_type}}"
    }
   ]
  }
 ]
}