scrape_configs:
  - job_name: andersonba
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: /metrics
    scheme: http
    params:
      url:
        - www.andersonba.com
      labels:
        - "site:andersonba"
    static_configs:
      - targets: ["server:3000"]
